server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: file:${HOME}/Documents/projects/widget-docker-demo/config-server-repo

---

spring:
  profiles: development

---

spring:
  profiles: production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/garystafford/microservice-docker-demo-config-repo.git

server:
  port: 0